WHeelOfLifeApp/Models/Admin/CreateRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WheelOfLifeApp.Models.Admin
{
    public class CreateRoleViewModel
    {
        [Required]
        public string RoleName { get; set; }
    }
}

WHeelOfLifeApp/Models/Admin/EditRole.cs
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WheelOfLifeApp.Models.Auth;

namespace WheelOfLifeApp.Models.Admin
{
    public class RoleEditModel
    {
        public IdentityRole Role { get; set; }
        public IEnumerable<ApplicationUser> Members { get; set; }
        public IEnumerable<ApplicationUser> NonMembers { get; set; }
    }

    public class RoleModificationModel
    {
        [Required]
        public string RoleName { get; set; }
        public string[] IdsToAdd { get; set; }
        public string[] IdsToDelete { get; set; }
    }
}

WHeelOfLifeApp/Controllers/AdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using WheelOfLifeApp.Models;
using WheelOfLifeApp.Models.Admin;
using WheelOfLifeApp.Models.Auth;
using WHeelOfLifeApp.Models.Auth;

namespace WheelOfLifeApp.Controllers
{
    [ExtendedAuthorize(Roles = "Администратор", RedirectUrl = "/Errors/UnauthorizedRequest")]
    public class AdminController : Controller
    {
        ApplicationDbContext context;

        private ApplicationDbContext DbContext
        {
            get
            {
                if (context == null) context = new ApplicationDbContext();
                return context;
            }
        }

        private UserManager UserManager
        {
            get { return new UserManager(new UserStore<ApplicationUser>(DbContext)); }
        }

        private RoleManager<IdentityRole> RoleManager
        {
            get { return new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(DbContext)); }
        }
        
        
        // GET: Admin
        public ActionResult Index()
        {
            ApplicationDbContext context = new ApplicationDbContext();
            ViewBag.Users = context.Users.ToList();
            ViewBag.Roles = context.Roles.ToList();
            return View();
        }

        public ActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateRole(CreateRoleViewModel role)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await RoleManager.CreateAsync(new IdentityRole(role.RoleName));

                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    AddErrorsFromResult(result);
            }
            return View(role);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteRole(string id)
        {
            IdentityRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await RoleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    return View("Error", result.Errors);
            }
            else
                return View("Error", new string[] { "Роль не найдена" });
        }

        [HttpPost]
        public async Task<ActionResult> DeleteUser(string id)
        {
            ApplicationUser user = await UserManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await UserManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    return View("Error", result.Errors);
            }
            else
                return View("Error", new string[] { "Пользователь не найден" });
        }

        public async Task<ActionResult> EditRole(string id)
        {
            IdentityRole role = await RoleManager.FindByIdAsync(id);
            string[] memberIds = role.Users.Select(x => x.UserId).ToArray();

            IEnumerable<ApplicationUser> members = UserManager.Users.Where(x => memberIds.Any(y => y == x.Id));
            IEnumerable<ApplicationUser> nonMembers = UserManager.Users.Except(members);

            return View(new RoleEditModel { Role = role, Members = members, NonMembers = nonMembers });
        }

        [HttpPost]
        public async Task<ActionResult> EditRole(RoleModificationModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsToAdd ?? new string[] { })
                {
                    result = await UserManager.AddToRoleAsync(userId, model.RoleName);

                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                foreach (string userId in model.IdsToDelete ?? new string[] { })
                {
                    result = await UserManager.RemoveFromRoleAsync(userId,
                    model.RoleName);

                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                return RedirectToAction("Index");

            }
            return View("Error", new string[] { "Роль не найдена" });
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}

WHeelOfLifeApp/Controllers/AuthController.cs
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using WheelOfLifeApp.Models.Auth;
using System.Web;
using System.Web.Mvc;
using WheelOfLifeApp.Models;
using System.Security.Claims;
using Microsoft.Owin.Security;
using System.Web.Configuration;
using Microsoft.AspNet.Identity.EntityFramework;

namespace WheelOfLifeApp.Controllers
{
    public class AuthController : Controller
    {
        ApplicationDbContext context;

        private IAuthenticationManager AuthManager
        {
            get { return HttpContext.GetOwinContext().Authentication; }
        }

        private ApplicationDbContext DbContext
        {
            get
            {
                if (context == null) context = new ApplicationDbContext();
                return context;
            }
        }

        private UserManager UserManager
        {
            get { return new UserManager(new UserStore<ApplicationUser>(DbContext)); }
        }

        private RoleManager<IdentityRole> RoleManager
        {
            get { return new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(DbContext)); }
        }

        [AllowAnonymous]
        public ActionResult LogIn(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LogIn(Login details, string returnUrl)
        {
            returnUrl = string.IsNullOrEmpty(returnUrl) ? "/" : returnUrl;
            UserStore Store = new UserStore(new ApplicationDbContext());
            UserManager userManager = new UserManager(Store);
            ApplicationUser user = await userManager.FindAsync(details.EmailOrUsername, details.Password);
            if (user == null)
            {
                user = await userManager.FindByEmailAsync(details.EmailOrUsername);
                if (user != null)
                    user = await userManager.CheckPasswordAsync(user, details.Password) ? user : null;
            }

            if (user == null)
                ModelState.AddModelError("", "Неверно введено имя пользователя или пароль.");
            else
            {
                ClaimsIdentity ident = await userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
                AuthManager.SignOut();
                AuthManager.SignIn(new AuthenticationProperties
                {
                    IsPersistent = false
                }, ident);
                return Redirect(returnUrl);
            }

            return View(details);                
        }

        public ActionResult LogOut(string returnUrl)
        {
            AuthManager.SignOut();
            return Redirect(returnUrl);
            //return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Register(Register model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser { UserName = model.Username, Email = model.Email };
                IdentityResult result = await UserManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    string defaultRoleName = WebConfigurationManager.AppSettings["defaultUserRole"];
                    IdentityResult iresult = await UserManager.AddToRoleAsync(user.Id, defaultRoleName);
                    if (iresult.Succeeded)
                        return RedirectToAction("Index", "Home", null);
                    else
                        return View("Error", new string[] { "Ошибка регистрации." });
                }
                else
                    AddErrorsFormResult(result);
            }
            return View(model);
        }

        private void AddErrorsFormResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
                ModelState.AddModelError("", error);
        }
    }
}

WHeelOfLifeApp/Views/Admin/CreateRole.cshtml
@model WheelOfLifeApp.Models.Admin.CreateRoleViewModel
@{
    ViewBag.Title = "Создание роли";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Создать роль</h2>
@Html.ValidationSummary(false)
@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Название</label>
        @Html.TextBoxFor(x => x.RoleName, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Создать</button>
    @Html.ActionLink("Отмена", "Index", null, new { @class="btn btn-default"})
}

WHeelOfLifeApp/Views/Admin/EditRole.cshtml
@using WheelOfLifeApp.Models.Admin
@using WheelOfLifeApp.Models.Auth
@model RoleEditModel
@{
    ViewBag.Title = "Изменить роль";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Изменить роль</h2>
@Html.ValidationSummary()
@using (Html.BeginForm())
{
    <input type="hidden" name="roleName" value="@Model.Role.Name"/>
    <div class="panel panel-primary">
        <div class="panel-heading">Добавить в роль <b>@Model.Role.Name</b></div>
        <table class="table table-striped">
            @if (Model.NonMembers.Count() == 0)
            {
                <tr>
                    <td colspan="2">Все пользователи в роли</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>User ID</td>
                    <td>Добавить в роль</td>
                </tr>
                foreach (ApplicationUser user in Model.NonMembers)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToAdd" value="@user.Id">
                        </td>
                    </tr>
                }
            }
        </table>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">Удалить из роли <b>@Model.Role.Name</b></div>
        <table class="table table-striped">
            @if (Model.Members.Count() == 0)
            {
                <tr>
                    <td colspan="2">Нет пользователей в роли</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>User ID</td>
                    <td>Удалить из роли</td>
                </tr>
                foreach (ApplicationUser user in Model.Members)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToDelete" value="@user.Id">
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
}

WHeelOfLifeApp/Views/Admin/Index.cshtml
@using WheelOfLifeApp.Models.Auth;
@using Microsoft.AspNet.Identity.EntityFramework;
@*@model IEnumerable<ApplicationUser>*@

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="panel panel-primary">
    <h3 class="panel-heading">Панель администрирования</h3>
    <div class="panel-body">
        <ul class="nav nav-pills">
            <li class="active"><a href="#users" data-toggle="tab">Пользователи</a></li>
            <li><a href="#roles" data-toggle="tab">Роли</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="users">
                <div class="panel-heading">
                    Учетные записи
                </div>
                <table class="table table-striped table-hover">
                    <tr>
                        <th>Id</th>
                        <th>Имя</th>
                        <th>Email</th>
                        <th style="min-width: 150px"></th>
                    </tr>
                    @if (ViewBag.Users.Count == 0)
                    {
                        <tr>
                            <td colspan="4" class="text-center">Нет ни одной учетной записи</td>
                        </tr>
                    }
                    else
                    {
                        foreach (ApplicationUser user in ViewBag.Users)
                        {
                            <tr>
                                <td>@user.Id</td>
                                <td>@user.UserName</td>
                                <td>@user.Email</td>
                                <td>
                                    @using (Html.BeginForm("DeleteUser", "Admin", new { id = user.Id }))
                                    {
                                        <button class="btn btn-danger btn-xs" type="submit">Удалить</button>
                                    }
                                </td>
                            </tr>
                        }
                    }
                </table>
                @Html.ActionLink("Добавить пользователя", "Register", "Auth", null, new { @class = "btn btn-primary" })
            </div>
            <div class="tab-pane" id="roles">
                <div>
                    <div class="panel-heading">
                        Роли
                    </div>
                    <table class="table table-striped table-hover">
                        <tr>
                            <th>Id</th>
                            <th>Название</th>
                            <th class="text-center">Пользователей в роли</th>
                            <th style="min-width: 150px"></th>
                        </tr>
                        @if (ViewBag.Roles?.Count == 0)
                        {
                            <tr>
                                <td colspan="4" class="text-center">Нет ни одной роли</td>
                            </tr>
                        }
                        else
                        {
                            foreach (IdentityRole role in ViewBag.Roles)
                            {
                                <tr>
                                    <td>@role.Id</td>
                                    <td>@role.Name</td>
                                    <td>
                                        @if (role.Users?.Count == 0)
                                        {
                                            @: Нет пользователей в этой роли.
                                        }
                                        else
                                        {
                                            @role.Users.Count
                                        }
                                    </td>
                                    <td>
                                        @using (Html.BeginForm("DeleteRole", "Admin", new { id = role.Id }))
                                        {
                                            @Html.ActionLink("Изменить", "EditRole", new { id = role.Id },
                                                new { @class = "btn btn-primary btn-xs", style = "float:left; margin-right:5px" })
                                            <button class="btn btn-danger btn-xs" type="submit">Удалить</button>
                                        }
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                    @Html.ActionLink("Добавить роль", "CreateRole", "Admin", null, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
    </div>
</div>